researchgate/gradle-release

src/main/groovy/release/HgReleasePlugin.groovy

A Mercurial release build should only check the current branch for
incoming changes instead of all branches.

Only check if update is needed on current branch for Mercurial

---

README.md
src/main/groovy/net/researchgate/release/PluginHelper.groovy
src/main/groovy/net/researchgate/release/ReleasePluginConvention.groovy
src/test/groovy/net/researchgate/release/PluginHelperTagNameTests.groovy

This allows setting tagTemplate in the configuration. tagTemplate is a string that gets evaluated as a template. Possible values are $version and $name.
So it might look something like:
"$version" -> 1.0.0
"v$version" -> v1.0.0
"$name-$version" -> project-1.0.0
"custom-$version" -> custom-1.0.0
Also deprecated tagPrefix and includeProjectNameInTag configurations.

Added tagTemplate configuration

---

src/main/groovy/net/researchgate/release/SvnAdapter.groovy

Currently we make use of a directory structure within our SVN 'tags' directory. Hereby we create some subdirectories based on major and major.minor versions of our tags. We can now achieve this behavior with the tagTemplate option (at least partly). 
Some examples:
```
/tags/1/1.20/1.20.1.5
```
Corresponding tag template:
```
'${ version.tokenize(".")[0] }/${ version.tokenize(".")[0] + "." + version.tokenize(".")[1] }/${version}'
```
The caveat is that SVN does not create the intermediate directories by default, therefore we need the `--parents` option, which is where this pull request is for.

support for creating intermediate directories with SVN tagging

---

README.md
src/main/groovy/net/researchgate/release/GitAdapter.groovy
src/test/groovy/net/researchgate/release/GitReleasePluginTests.groovy

Added a fix to allow setting a regular expression as a value for the release.git.requireBranch property

Setting requireBranch property to a regular expressions #118

---

CHANGELOG.md
README.md
src/main/groovy/net/researchgate/release/GitAdapter.groovy
src/test/groovy/net/researchgate/release/GitReleasePluginCommitNewVersionTests.groovy

When using a review system like gerrit, commits are pushed to
special branches. Instead of pushing simply to 'master', one
needs to push to 'refs/for/master'.
An option 'pushToBranchPrefix' was added to the git adapter to
be able to achieve this.

Add a pushToBranchPrefix option to git adapter

---

src/main/groovy/net/researchgate/release/PluginHelper.groovy
src/test/groovy/net/researchgate/release/PluginHelperVersionPropertyFileTests.groovy

The current version has a bug when releasing with automatic update of the version where all properties in gradle.properties that end in "version" get updated with the new version.
I.e. For properties defined as:
version=1.1-SNAPSHOT
another.lib.version=5.0
Both properties get a new version of 1.2-SNAPSHOT
This branch fixes the issue and includes a test that exposes the issue if the fix is not applied.

Fixed update version problem that updated all props ending in "version"

---

CHANGELOG.md
README.md
src/main/groovy/net/researchgate/release/GitAdapter.groovy
src/test/groovy/net/researchgate/release/GitReleasePluginCommitNewVersionTests.groovy

An option 'commitVersionFileOnly' will be useful when we want to avoid build server script changing git indexed file.
Change-Id: I333b9e0f668deb64b4055db9ef0653540522ae90

An option 'commitVersionFileOnly' will be useful when we want to avoid build server script changing git indexed file.

---

README.md
build.gradle
gradle.properties
src/main/groovy/net/researchgate/release/SvnAdapter.groovy
src/test/groovy/net/researchgate/release/SvnAdapterTests.groovy

The new SVN client (v1.9) supports the --pin-externals flag, which allows to fix externals to a specific revision when creating the tag.

SVN: support for --pin-externals of SVN 1.9 or later

---

.gitignore
CHANGELOG.md
README.md
src/main/groovy/net/researchgate/release/GitAdapter.groovy
src/test/groovy/net/researchgate/release/GitReleasePluginTests.groovy

our build runs static analysis and tests during a push. this makes the tagging process terribly slow (10+ minutes). This will permit me to skip those checks by supplying pushOptions = ["--no-verify"]

add a new option to the plugin to support other options during push

---

src/main/groovy/net/researchgate/release/cli/Executor.groovy

Some systems will always output messages to stderr. Instead of using this to determine errors, executor should use the process' exit value. Non-zero values are errors.

CLI Executor now detects error from process exitValue

---

src/main/groovy/net/researchgate/release/ReleasePlugin.groovy

This PR fixes `The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.` warnings that have been introduced in Gradle 3.2.
I verified the patch by temporarily upgrading the Gradle version of the build to 3.2 (and Spock to `1.0-groovy-2.4`). The tests caused the deprecation warnings before applying this patch and the warnings vanished with the patch in place.
Existing tests are still running with the patch in place.

Fixes Task.leftShift(Closure) deprecation warnings

---

src/main/groovy/net/researchgate/release/GitAdapter.groovy
src/main/groovy/net/researchgate/release/ReleasePlugin.groovy

Our project setup is done with google repo and it looks like this
main
|
|-- module
|    |--.git
|    |-- build.gradle
|
| -- module1
|      |-- build.gradle
|      | -- sub-module
|             |--.git
|             |-- build.gradle (Use release plugin here)
|- build.gradle (Use release plugin here)
And I want to be able to release "module1:sub-module" and main. But they should use their respective git repositories. After some testing I found out that the code did not support this.
So this is a possible solution for git.

Support repo setup for submodule/-projects

---

src/main/groovy/net/researchgate/release/ReleasePlugin.groovy
src/test/groovy/net/researchgate/release/ReleasePluginCheckSnapshotDependenciesTests.groovy

This Pull Request fixes #230 by adding a check to the aforementioned task to check the buildscript dependencies too. Tests for the task have been updated too.

Fixed checkSnapshotDependencies task to check the buildscript dependencies.

---

README.md
src/main/groovy/net/researchgate/release/ReleaseExtension.groovy
src/main/groovy/net/researchgate/release/ReleasePlugin.groovy
src/test/groovy/net/researchgate/release/ReleasePluginCheckSnapshotDependenciesTests.groovy

Fix for #247 
* Add a new list in which we can provide the name of artifact to ignore
* Add a test in the matcher to check whether the dependency should be ignored

#247: Allow to ignore some snapshot dependencies

---

.gitignore
README.md
src/main/groovy/net/researchgate/release/BaseScmAdapter.groovy
src/main/groovy/net/researchgate/release/GitAdapter.groovy
src/main/groovy/net/researchgate/release/ReleaseExtension.groovy
src/main/groovy/net/researchgate/release/ReleasePlugin.groovy
src/test/groovy/net/researchgate/release/GitReleasePluginTests.groovy

Following submitted issue #195, I would like to propose an implementation of the asked functionnality on this PR, available for now only on GIT repositories.
Namely, this option allows to push the release commit (and the associated tag) on a release branch, and the new snapshot commit to the working branch (typically master). Of course the release commit is also a full-merge commit of the working branch at the time of the `release` task launch. This option is compatible with CI systems who publish releases from the release branch and snapshots from the working branch.
This functionality is activated by setting the property `pushReleaseVersionBranch` to the name of the release branch. By default, this property is setted to false and deactivate the functionality.
Typical example :
<pre> …

Add option pushReleaseVersionBranch to push release commit on a specific branch

---

.travis.yml
src/test/groovy/net/researchgate/release/ReleasePluginTests.groovy

This PR is extending the ReleasePluginTests to validate the methods `unSnapshotVersion` and `updateVersion` against various semantic versions.
Right now 4 tests are failing since they do not handle properly [semver metadata](https://semver.org/#spec-item-10). Most likely due to the default `versionPattern`.

chore: extend tests to cover various semantic versions

---

build.gradle

JFrog JCenter does not allow HTTP anymore; the rather old gradle version probably defaults to an HTTP URL. This change might gradle lead to use the HTTPS URL.

Use HTTPS for JCenter

---

README.md

The configuration example in the bottom of the readme doesn't work for 2.6.0 (the option pushReleaseVersionBranch wasnt available)

Update plugin version to 2.8.1 in readme

---

README.md

failOnCommitNeeded commits files automatically if set to false. Neither README nor plugin output does state this clearly.

Note auto commit if failOnCommitNeeded=false

---

src/main/groovy/net/researchgate/release/ReleasePlugin.groovy

Fixes #330 
Setting _buildName_ to a slightly modified name in order to play nice with Gradle 6: https://github.com/gradle/gradle/issues/12872

Gradle 6 Workaround for multi-project release

---

README.md
src/main/groovy/net/researchgate/release/GitAdapter.groovy
src/test/groovy/net/researchgate/release/GitReleasePluginTests.groovy

Proposal for adding git commit options.
This means a user can do something like ["-s"] to satisfy DCO bots: https://github.com/apps/dco

Proposal to add `commitOptions` to git config -- Update GitAdapter.groovy

---

src/main/groovy/net/researchgate/release/GitAdapter.groovy

requireBranch is always present due to the convention on the property. Even when overriding to empty string or null it is still considered present.

Fix to allow releases on any Git branch

---

src/main/groovy/net/researchgate/release/tasks/PreTagCommit.groovy

Do not add an excessive space in the pre tag commit message if no pre commit text is set

---

src/test/groovy/net/researchgate/release/ReleasePluginTests.groovy

Without this, the test fails on Windows due to different line end sequence.

Make test cross-OS safe

---

src/test/groovy/net/researchgate/release/GitReleasePluginTests.groovy

Test case "commitOptions are passed through to git command" would fail on my machine due to custom pretty format settings:
~/.gitconfig:
```
[format]
pretty = %Cgreen%ci:%C(yellow)%d%Creset|%G?|%s (%Cred%h%Creset by %C(bold blue)%an%Creset) %ae [%GS]
```
This resulted in the following test failure:
```
Condition not satisfied:
newestCommit.contains("Signed-off-by: Unit Test <unit@test>")
|            |
|            false
2023-03-26 15:23:54 +0200: (myBranch)|N|[Gradle Release Plugin] - new version commit:  '1.1'. (40b3a21 by Unit Test) unit@test []
at net.researchgate.release.GitReleasePluginTests.commitOptions are passed through to git command(GitReleasePluginTests.groovy:133)
```
This is a simple fix which tells the test to request the information it needs ("pretty=medium") rather than …

Fix GitReleasePluginTests when global .gitconfig contains custom pretty format settings
